#!/bin/bash
#

function add
{
  echo "`expr $1 + $2`" 
}

function reduce
{
  echo "`expr $1 - $2`"
}

function multiple
{
  echo "`expr $1 \* $2`"
}

function divide
{
  echo "`expr $1 / $2`"
}

function sys_load
{
  echo "Memory Info"
  echo 
  free -m
  echo 
  echo "Dis Usage"
  df -h
  echo
}
